/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import countdown.CalcSequence;
import countdown.Solver;
import countdown.Util;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class MainPanel extends javax.swing.JPanel {
    Solver solver;
    ArrayList<CalcSequence> calcs;
    JFrame parent;
    ResultsFrame results;
    /**
     * Creates new form MainPanel
     * @param parent
     */
    public MainPanel(JFrame parent) {
        calcs = new ArrayList<>();
        initComponents();
        this.parent = parent;
        results = new ResultsFrame();
    }
    public void setResultsToTable(){
        
        String[] columnNames = {"Calculation","Size","Numbers Used", "Value"};
        calcTable.setModel(Util.genTableModelFromCalcList(calcs, columnNames));
        revalidate();
        repaint();
    }
    public void setNumberOfInputs(int n){
        enterNumbersPanel3.setNumberOfInputs(n);
        revalidate();
       // repaint();
    }
    public void addSolution(CalcSequence seq){
        calcs.add(seq);
        setResultsToTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterNumbersPanel1 = new gui.EnterNumbersPanel();
        enterNumbersPanel3 = new gui.EnterNumbersPanel();
        enterTargetField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        calcTable = new javax.swing.JTable();
        changeInputsField = new javax.swing.JTextField();
        changeInputsButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout enterNumbersPanel1Layout = new javax.swing.GroupLayout(enterNumbersPanel1);
        enterNumbersPanel1.setLayout(enterNumbersPanel1Layout);
        enterNumbersPanel1Layout.setHorizontalGroup(
            enterNumbersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        enterNumbersPanel1Layout.setVerticalGroup(
            enterNumbersPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        enterTargetField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        enterTargetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTargetFieldActionPerformed(evt);
            }
        });

        calcTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Calculation", "Size", "Numbers Used", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(calcTable);

        changeInputsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeInputsFieldActionPerformed(evt);
            }
        });

        changeInputsButton.setText("Set Inputs");
        changeInputsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeInputsButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Target");

        jLabel2.setText("Numbers");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(enterNumbersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(changeInputsField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeInputsButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(enterNumbersPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enterTargetField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(enterNumbersPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(enterTargetField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(enterNumbersPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeInputsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeInputsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterTargetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTargetFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterTargetFieldActionPerformed

    private void changeInputsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeInputsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeInputsFieldActionPerformed

    private void changeInputsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeInputsButtonActionPerformed
        try{
            int n = Integer.parseInt(changeInputsField.getText());
            if(n>12||n<1){
                new JDialog(parent,"Please enter an integer between 1 and 12",true);
                changeInputsField.setText("");
            }
            
            enterNumbersPanel3.setNumberOfInputs(n);
            revalidate();
            repaint();
            
        }
        catch(NumberFormatException e){
            new JDialog(parent,"Please enter an integer between 1 and 12",true);
            changeInputsField.setText("");
        }
    }//GEN-LAST:event_changeInputsButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        calcs.clear();
        try{
            
            solver = new Solver(enterNumbersPanel3.getNumbers(), Integer.parseInt(enterTargetField.getText()),results);
            solver.expand();
            solver.expand();
            solver.expand();
            solver.expand();
            solver.expand();
            
        }
        catch(NumberFormatException e){
            new JDialog(parent,"Please enter an integer for the target");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable calcTable;
    private javax.swing.JButton changeInputsButton;
    private javax.swing.JTextField changeInputsField;
    private gui.EnterNumbersPanel enterNumbersPanel1;
    private gui.EnterNumbersPanel enterNumbersPanel3;
    private javax.swing.JTextField enterTargetField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
